'use client';

import React, { useState, useRef, useEffect } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { createClient } from '@/utils/supabase/client';
import { useAuth } from '@/contexts/AuthContext';

// Konfigurasi Gardu Induk (untuk multi-login di masa depan)
// TODO: Ganti dengan dynamic dari AuthContext setelah login terintegrasi
const KODE_GARDU = 'batang';  // Sekarang lowercase, nanti dari auth context

// Types
interface Equipment {
    id: string;  // UUID auto-generated by Supabase
    nama_lengkap: string;
    type: string;
    section: string;
    bay: string;
    kode_gardu?: string;
    created_at?: string;
    updated_at?: string;  // Timestamp saat terakhir diedit
}

// Animation Variants
const rowVariants = {
    hidden: { opacity: 0, x: -50, scale: 0.98 },
    visible: {
        opacity: 1,
        x: 0,
        scale: 1,
        transition: { type: "spring" as const, stiffness: 300, damping: 25 }
    },
    exit: {
        opacity: 0,
        x: 80,
        scale: 0.98,
        transition: { type: "tween" as const, duration: 0.25, ease: "easeOut" as const }
    }
};

// Helper: Normalize voltage patterns (e.g., "150KV" -> "150 KV", "20  KV" -> "20 KV")
function normalizeVoltage(text: string): string {
    // Match patterns like "150KV", "20 KV", "70  KV" and normalize to "XXX KV"
    return text.replace(/(\d+)\s*KV/gi, '$1 KV');
}

// Helper: Parse equipment name to get type and section
function parseEquipmentName(name: string): { type: string; section: string } {
    const words = name.trim().toUpperCase().split(/\s+/);
    const type = words[0] || '';
    const section = words.slice(1).join(' ');
    return { type, section };
}

export default function DataAlat() {
    const [equipmentList, setEquipmentList] = useState<Equipment[]>([]);
    // Undo stack: stores action type and affected item (for edit: also stores old values)
    const [history, setHistory] = useState<{ action: 'add' | 'delete' | 'edit'; item: Equipment; oldItem?: Equipment }[]>([]);
    const [isUndoing, setIsUndoing] = useState(false);
    const [isLoading, setIsLoading] = useState(true);
    const [isSaving, setIsSaving] = useState(false);
    const [newEquipment, setNewEquipment] = useState({ name: '', bay: '' });
    const [isConfirmOpen, setIsConfirmOpen] = useState(false);
    const [formError, setFormError] = useState<string | null>(null);
    const [newRowId, setNewRowId] = useState<string | null>(null);
    const [isInitialLoad, setIsInitialLoad] = useState(true);  // Skip animation on first load
    const [filterBay, setFilterBay] = useState<string | null>(null);  // Bay filter
    // Edit modal state
    const [editingItem, setEditingItem] = useState<Equipment | null>(null);
    const [editData, setEditData] = useState({ name: '', bay: '' });
    const [editError, setEditError] = useState<string | null>(null);
    const tableContainerRef = useRef<HTMLDivElement>(null);

    const supabase = createClient();
    const { profile, isMaster } = useAuth();

    // Get current user's kode_gardu
    const userKodeGardu = profile?.kode_gardu || KODE_GARDU;

    // Fetch data from Supabase on mount & when profile changes
    useEffect(() => {
        if (profile || isMaster) {
            fetchEquipment();
        }
    }, [profile, isMaster]);

    // Auto-scroll to top when new row added
    useEffect(() => {
        if (newRowId && tableContainerRef.current) {
            tableContainerRef.current.scrollTo({ top: 0, behavior: 'smooth' });
        }
    }, [newRowId]);

    const fetchEquipment = async () => {
        setIsLoading(true);

        // Build query - master sees all, others see only their gardu
        let query = supabase
            .from('peralatan')
            .select('*')
            .order('created_at', { ascending: false });

        // Filter by kode_gardu if not master
        if (!isMaster && userKodeGardu) {
            query = query.eq('kode_gardu', userKodeGardu);
        }

        const { data, error } = await query;

        if (error) {
            console.error('Error fetching equipment:', error);
        } else {
            setEquipmentList(data || []);
        }
        setIsLoading(false);
        // After initial load, enable animations
        setTimeout(() => setIsInitialLoad(false), 100);
    };

    const pushToHistory = (action: 'add' | 'delete' | 'edit', item: Equipment, oldItem?: Equipment) => {
        setHistory((prev) => [...prev.slice(-19), { action, item, oldItem }]); // Keep max 20 history
    };

    const undo = async () => {
        if (history.length === 0 || isUndoing) return;

        setIsUndoing(true);
        const lastAction = history[history.length - 1];

        try {
            if (lastAction.action === 'add') {
                // Undo add = delete from Supabase
                const { error } = await supabase
                    .from('peralatan')
                    .delete()
                    .eq('id', lastAction.item.id);

                if (!error) {
                    setEquipmentList((prev) => prev.filter((item) => item.id !== lastAction.item.id));
                    setHistory((prev) => prev.slice(0, -1));
                } else {
                    console.error('Undo add failed:', error);
                }
            } else if (lastAction.action === 'delete') {
                // Undo delete = re-insert to Supabase (with original ID)
                const { data, error } = await supabase
                    .from('peralatan')
                    .insert({
                        id: lastAction.item.id,  // Keep original ID for undo
                        nama_lengkap: lastAction.item.nama_lengkap,
                        type: lastAction.item.type,
                        section: lastAction.item.section,
                        bay: lastAction.item.bay,
                        kode_gardu: lastAction.item.kode_gardu || userKodeGardu
                    })
                    .select()
                    .single();

                if (!error && data) {
                    setEquipmentList((prev) => [data, ...prev]);
                    setHistory((prev) => prev.slice(0, -1));
                } else {
                    console.error('Undo delete failed:', error);
                }
            } else if (lastAction.action === 'edit' && lastAction.oldItem) {
                // Undo edit = restore old values to Supabase
                const { error } = await supabase
                    .from('peralatan')
                    .update({
                        nama_lengkap: lastAction.oldItem.nama_lengkap,
                        type: lastAction.oldItem.type,
                        section: lastAction.oldItem.section,
                        bay: lastAction.oldItem.bay
                    })
                    .eq('id', lastAction.oldItem.id);

                if (!error) {
                    setEquipmentList((prev) => prev.map((item) =>
                        item.id === lastAction.oldItem!.id ? lastAction.oldItem! : item
                    ));
                    setHistory((prev) => prev.slice(0, -1));
                } else {
                    console.error('Undo edit failed:', error);
                }
            }
        } catch (err) {
            console.error('Undo error:', err);
        }

        setIsUndoing(false);
    };

    const handleAdd = async () => {
        // Normalize voltage patterns (e.g., "150KV" -> "150 KV")
        const trimmedName = normalizeVoltage(newEquipment.name.trim().toUpperCase());
        const trimmedBay = normalizeVoltage(newEquipment.bay.trim().toUpperCase());

        // Validation: Both fields required
        if (!trimmedName || !trimmedBay) {
            setFormError('Lengkapi nama peralatan dan bay!');
            setTimeout(() => setFormError(null), 2000);
            return;
        }

        // Validation: Name must have at least 2 words
        const wordCount = trimmedName.split(/\s+/).length;
        if (wordCount < 2) {
            setFormError('Nama peralatan harus minimal 2 kata!');
            setTimeout(() => setFormError(null), 2000);
            return;
        }

        // Construct full name early for duplicate check
        const namaLengkap = `${trimmedName} ${trimmedBay}`;

        // Validation: Check for duplicate
        const isDuplicate = equipmentList.some(item => item.nama_lengkap === namaLengkap);
        if (isDuplicate) {
            setFormError(`${namaLengkap} sudah ada!`);
            setTimeout(() => setFormError(null), 3000);
            return;
        }

        setIsSaving(true);

        try {
            // Parse name to get type and section
            const { type, section } = parseEquipmentName(trimmedName);

            // Insert to Supabase (ID is auto-generated by Supabase)
            const { data, error } = await supabase
                .from('peralatan')
                .insert({
                    nama_lengkap: namaLengkap,
                    type: type,
                    section: section,
                    bay: trimmedBay,
                    kode_gardu: userKodeGardu
                })
                .select()
                .single();

            if (error) {
                console.error('Error adding equipment:', error.message, error.details, error.hint, error.code);
                setFormError(`Gagal: ${error.message || 'Unknown error'}`);
                setTimeout(() => setFormError(null), 3000);
            } else if (data) {
                pushToHistory('add', data);
                setEquipmentList([data, ...equipmentList]);
                setNewEquipment({ name: '', bay: '' });
                setNewRowId(data.id);
                setTimeout(() => setNewRowId(null), 600);
            }
        } catch (err) {
            console.error('Error:', err);
            setFormError('Terjadi kesalahan!');
            setTimeout(() => setFormError(null), 2000);
        }

        setIsSaving(false);
    };

    const handleDelete = async (id: string) => {
        const itemToDelete = equipmentList.find((item) => item.id === id);
        if (!itemToDelete) return;

        const { error } = await supabase
            .from('peralatan')
            .delete()
            .eq('id', id);

        if (error) {
            console.error('Error deleting equipment:', error);
        } else {
            pushToHistory('delete', itemToDelete);
            setEquipmentList(equipmentList.filter((item) => item.id !== id));
        }
    };

    const confirmClearAll = async () => {
        // Delete all from Supabase
        const { error } = await supabase
            .from('peralatan')
            .delete()
            .neq('id', ''); // Delete all rows

        if (error) {
            console.error('Error clearing all:', error);
        } else {
            setEquipmentList([]);
        }
        setIsConfirmOpen(false);
    };

    // Start editing an item
    const startEdit = (item: Equipment) => {
        // Parse nama_lengkap to extract name (type + section) and bay
        // nama_lengkap format: "PMS BUS A BREBES 1" where bay is the last part
        const parts = item.nama_lengkap.split(' ');
        // Find where bay starts - bay is stored separately so we can use it
        const bayParts = item.bay.split(' ');
        const bayStartIndex = parts.length - bayParts.length;
        const namePart = parts.slice(0, bayStartIndex).join(' ');

        setEditingItem(item);
        setEditData({ name: namePart, bay: item.bay });
        setEditError(null);
    };

    // Save edited item
    const handleSaveEdit = async () => {
        if (!editingItem) return;

        // Normalize voltage patterns
        const trimmedName = normalizeVoltage(editData.name.trim().toUpperCase());
        const trimmedBay = normalizeVoltage(editData.bay.trim().toUpperCase());

        // Validation: Both fields required
        if (!trimmedName || !trimmedBay) {
            setEditError('Lengkapi nama peralatan dan bay!');
            return;
        }

        // Validation: Name must have at least 2 words
        const wordCount = trimmedName.split(/\s+/).length;
        if (wordCount < 2) {
            setEditError('Nama peralatan harus minimal 2 kata!');
            return;
        }

        // Construct full name
        const newNamaLengkap = `${trimmedName} ${trimmedBay}`;

        // Validation: Check for duplicate (excluding current item)
        const isDuplicate = equipmentList.some(
            item => item.id !== editingItem.id && item.nama_lengkap === newNamaLengkap
        );
        if (isDuplicate) {
            setEditError(`${newNamaLengkap} sudah ada!`);
            return;
        }

        setIsSaving(true);

        try {
            // Parse name to get type and section
            const { type, section } = parseEquipmentName(trimmedName);
            const now = new Date().toISOString();

            // Update in Supabase (keeps same ID)
            const { error } = await supabase
                .from('peralatan')
                .update({
                    nama_lengkap: newNamaLengkap,
                    type: type,
                    section: section,
                    bay: trimmedBay,
                    updated_at: now
                })
                .eq('id', editingItem.id);

            if (error) {
                console.error('Error updating equipment:', error);
                setEditError(`Gagal: ${error.message || 'Unknown error'}`);
            } else {
                // Create updated item
                const updatedItem: Equipment = {
                    ...editingItem,
                    nama_lengkap: newNamaLengkap,
                    type: type,
                    section: section,
                    bay: trimmedBay,
                    updated_at: now
                };

                // Push to history with old values for undo
                pushToHistory('edit', updatedItem, editingItem);

                // Update local state
                setEquipmentList(prev => prev.map(item =>
                    item.id === editingItem.id ? updatedItem : item
                ));

                // Close modal
                setEditingItem(null);
                setEditData({ name: '', bay: '' });
            }
        } catch (err) {
            console.error('Error:', err);
            setEditError('Terjadi kesalahan!');
        }

        setIsSaving(false);
    };

    // Cancel edit
    const cancelEdit = () => {
        setEditingItem(null);
        setEditData({ name: '', bay: '' });
        setEditError(null);
    };

    return (
        <>
            {/* Input Bar Section */}
            <div className="bg-white p-2 rounded-xl border border-orange-100 shadow-sm flex flex-col md:flex-row gap-2 mb-6 items-center relative">
                <div className="flex-1 w-full relative">
                    <div className="absolute inset-y-0 left-3 flex items-center pointer-events-none">
                        <svg className="w-4 h-4 text-gray-400" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 10V3L4 14h7v7l9-11h-7z" />
                        </svg>
                    </div>
                    <input
                        type="text"
                        placeholder="Nama Peralatan (contoh: PMS BUS A, PMT 20 KV)"
                        value={newEquipment.name}
                        onChange={(e) => setNewEquipment({ ...newEquipment, name: e.target.value.toUpperCase() })}
                        className={`w-full pl-10 pr-4 py-2 bg-slate-50 border-2 focus:bg-white focus:border-orange-300 focus:outline-none focus:ring-2 focus:ring-orange-100 rounded-lg transition-all text-sm uppercase ${formError && (!newEquipment.name.trim() || formError.includes('2 kata')) ? 'border-red-500 bg-red-100 ring-2 ring-red-200' : 'border-transparent'}`}
                        disabled={isSaving}
                    />
                </div>
                <div className="flex-1 w-full relative">
                    <div className="absolute inset-y-0 left-3 flex items-center pointer-events-none">
                        <svg className="w-4 h-4 text-gray-400" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 21V5a2 2 0 00-2-2H7a2 2 0 00-2 2v16m14 0h2m-2 0h-5m-9 0H3m2 0h5M9 7h1m-1 4h1m4-4h1m-1 4h1m-5 10v-5a1 1 0 011-1h2a1 1 0 011 1v5m-4 0h4" />
                        </svg>
                    </div>
                    <input
                        type="text"
                        placeholder="Nama Bay (contoh: BREBES 1)"
                        value={newEquipment.bay}
                        onChange={(e) => setNewEquipment({ ...newEquipment, bay: e.target.value.toUpperCase() })}
                        className={`w-full pl-10 pr-4 py-2 bg-slate-50 border-2 focus:bg-white focus:border-orange-300 focus:outline-none focus:ring-2 focus:ring-orange-100 rounded-lg transition-all text-sm uppercase ${formError && !newEquipment.bay.trim() ? 'border-red-500 bg-red-100 ring-2 ring-red-200' : 'border-transparent'}`}
                        disabled={isSaving}
                    />
                </div>
                <button
                    onClick={handleAdd}
                    disabled={isSaving}
                    className="w-full md:w-auto bg-orange-500 hover:bg-orange-600 active:scale-95 active:bg-orange-700 text-white font-medium px-6 py-2 rounded-lg transition-all flex items-center justify-center gap-2 shadow-sm disabled:opacity-50 disabled:cursor-not-allowed"
                >
                    {isSaving ? (
                        <svg className="animate-spin h-4 w-4" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
                            <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
                            <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
                        </svg>
                    ) : (
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
                            <line x1="12" y1="5" x2="12" y2="19"></line>
                            <line x1="5" y1="12" x2="19" y2="12"></line>
                        </svg>
                    )}
                    <span>{isSaving ? 'Menyimpan...' : 'Tambah'}</span>
                </button>

                {/* Form Error Notification */}
                <AnimatePresence>
                    {formError && (
                        <motion.div
                            initial={{ opacity: 0, scale: 0.9, y: 0, x: "-50%" }}
                            animate={{ opacity: 1, scale: 1, y: 0, x: "-50%" }}
                            exit={{ opacity: 0, scale: 0.5, y: -50, x: "-50%" }}
                            transition={{ duration: 0.3 }}
                            className="fixed top-1/3 left-1/2 z-50 text-red-600 text-sm font-bold font-sans italic tracking-tight drop-shadow-sm pointer-events-none whitespace-nowrap bg-orange-50/60 border border-orange-100/60 px-3 py-2 shadow-lg backdrop-blur-[2px]"
                        >
                            <span className="block">{formError}</span>
                        </motion.div>
                    )}
                </AnimatePresence>
            </div>

            {/* Data List Section */}
            <div className="bg-white rounded-xl border border-orange-100 shadow-sm flex flex-col h-[600px] overflow-hidden">
                <div ref={tableContainerRef} className="flex-1 overflow-auto w-full [&::-webkit-scrollbar]:w-3 [&::-webkit-scrollbar]:h-3 [&::-webkit-scrollbar-track]:bg-slate-50 [&::-webkit-scrollbar-thumb]:bg-slate-200 [&::-webkit-scrollbar-thumb]:rounded-full hover:[&::-webkit-scrollbar-thumb]:bg-slate-300">
                    <table className="w-full text-left border-collapse min-w-[420px]">
                        <thead className="sticky top-0 bg-orange-50/90 backdrop-blur-sm z-10 shadow-sm">
                            <tr>
                                <th className="py-2 px-1 font-semibold text-gray-600 text-xs w-8 border-b border-orange-100 text-center">No</th>
                                <th className="py-2 px-2 font-semibold text-gray-600 text-xs border-b border-orange-100">Nama Peralatan</th>
                                <th className="py-2 px-2 font-semibold text-gray-600 text-xs w-1/5 border-b border-orange-100">Bay</th>
                                <th className="py-2 px-1 font-semibold text-gray-600 text-xs w-20 border-b border-orange-100">
                                    <div className="flex items-center justify-center gap-3">
                                        <button
                                            onClick={undo}
                                            disabled={history.length === 0 || isUndoing}
                                            className={`text-xs font-medium px-2 py-1 rounded transition-colors ${history.length > 0 && !isUndoing
                                                ? 'bg-slate-100 text-slate-700 hover:bg-slate-200'
                                                : 'text-gray-300 cursor-not-allowed'
                                                }`}
                                            title="Undo Last Action"
                                        >
                                            {isUndoing ? '...' : 'Undo'}
                                        </button>
                                        <button
                                            onClick={() => setIsConfirmOpen(true)}
                                            className="text-xs font-medium text-red-500 hover:text-red-700 hover:underline"
                                            title="Clear All Data"
                                        >
                                            Clear
                                        </button>
                                    </div>
                                </th>
                            </tr>
                        </thead>
                        <tbody className="divide-y divide-slate-50">
                            <AnimatePresence mode="sync" initial={false}>
                                {isLoading ? (
                                    <motion.tr
                                        initial={{ opacity: 0 }}
                                        animate={{ opacity: 1 }}
                                        exit={{ opacity: 0 }}
                                    >
                                        <td colSpan={4} className="py-12 text-center text-gray-400 italic text-sm">
                                            <div className="flex items-center justify-center gap-2">
                                                <svg className="animate-spin h-5 w-5" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
                                                    <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
                                                    <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
                                                </svg>
                                                Memuat data...
                                            </div>
                                        </td>
                                    </motion.tr>
                                ) : equipmentList.length > 0 ? (
                                    equipmentList
                                        .filter(item => !filterBay || item.bay === filterBay)
                                        .map((item, index) => (
                                            <motion.tr
                                                key={item.id}
                                                variants={rowVariants}
                                                initial={isInitialLoad ? false : "hidden"}
                                                animate="visible"
                                                exit="exit"
                                                layout={!isInitialLoad}
                                                className={`hover:bg-orange-50/30 transition-colors group ${item.id === newRowId ? 'bg-orange-100' : ''}`}
                                            >
                                                <td className="py-1.5 px-1 text-gray-400 text-xs text-center w-8">{index + 1}</td>
                                                <td className="py-1.5 px-2 font-medium text-gray-800 text-xs break-words">{item.nama_lengkap}</td>
                                                <td className="py-1.5 px-2 text-gray-600 text-xs">
                                                    <button
                                                        onClick={() => setFilterBay(filterBay === item.bay ? null : item.bay)}
                                                        className={`px-2 py-0.5 rounded text-xs font-semibold tracking-wide transition-all cursor-pointer hover:scale-105 ${filterBay === item.bay ? 'bg-orange-500 text-white' : 'bg-slate-100 text-slate-600 hover:bg-slate-200'}`}
                                                        title={filterBay === item.bay ? 'Klik untuk hapus filter' : `Filter by ${item.bay}`}
                                                    >
                                                        {item.bay}
                                                    </button>
                                                </td>
                                                <td className="py-1.5 px-1 text-center">
                                                    <div className="flex items-center justify-center gap-0">
                                                        <button
                                                            onClick={() => startEdit(item)}
                                                            className="text-gray-400 hover:text-orange-500 active:scale-90 transition-all p-1"
                                                            title="Edit"
                                                        >
                                                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                                                                <path d="M11 4H4a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-7"></path>
                                                                <path d="M18.5 2.5a2.121 2.121 0 0 1 3 3L12 15l-4 1 1-4 9.5-9.5z"></path>
                                                            </svg>
                                                        </button>
                                                        <button
                                                            onClick={() => handleDelete(item.id)}
                                                            className="text-red-400 hover:text-red-600 active:scale-90 transition-all p-1"
                                                            title="Hapus"
                                                        >
                                                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                                                                <line x1="18" y1="6" x2="6" y2="18"></line>
                                                                <line x1="6" y1="6" x2="18" y2="18"></line>
                                                            </svg>
                                                        </button>
                                                    </div>
                                                </td>
                                            </motion.tr>
                                        ))
                                ) : (
                                    <motion.tr
                                        initial={{ opacity: 0 }}
                                        animate={{ opacity: 1 }}
                                        exit={{ opacity: 0 }}
                                    >
                                        <td colSpan={4} className="py-12 text-center text-gray-400 italic text-sm">
                                            Silahkan tambahkan data peralatan
                                        </td>
                                    </motion.tr>
                                )}
                            </AnimatePresence>
                        </tbody>
                    </table>
                </div>
            </div>

            {/* Scroll Indicator Hint & Refresh Button */}
            <div className="flex items-center justify-between mt-2 px-1">
                <div className="text-xs text-slate-400 md:hidden">
                    ← Geser untuk melihat tabel →
                </div>
                <button
                    onClick={() => fetchEquipment()}
                    className="text-xs font-medium px-3 py-1 rounded transition-colors bg-slate-100 text-slate-500 hover:bg-slate-200 hover:text-slate-700 ml-auto"
                    title="Refresh Data dari Server"
                >
                    ↻ Refresh
                </button>
            </div>

            {/* Confirmation Modal */}
            {isConfirmOpen && (
                <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 backdrop-blur-sm animate-in fade-in duration-200 p-4">
                    <div className="bg-white rounded-xl shadow-xl p-6 w-full max-w-sm animate-in zoom-in-95 duration-200">
                        <h3 className="text-lg font-bold text-gray-800 mb-2">Hapus Semua Data?</h3>
                        <p className="text-gray-600 text-sm mb-6 leading-relaxed">
                            Tindakan ini akan menghapus <strong>{equipmentList.length} item</strong> dari database. Data yang dihapus tidak dapat dikembalikan.
                        </p>
                        <div className="flex justify-end gap-3">
                            <button
                                onClick={() => setIsConfirmOpen(false)}
                                className="px-4 py-2 text-sm font-medium text-gray-700 bg-gray-100 hover:bg-gray-200 rounded-lg transition-colors"
                            >
                                Batal
                            </button>
                            <button
                                onClick={confirmClearAll}
                                className="px-4 py-2 text-sm font-medium text-white bg-red-500 hover:bg-red-600 rounded-lg transition-colors shadow-sm"
                            >
                                Ya, Hapus Semua
                            </button>
                        </div>
                    </div>
                </div>
            )}

            {/* Edit Modal - Subtle overlay, focus on task */}
            {editingItem && (
                <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/30 backdrop-blur-[2px] animate-in fade-in duration-150 p-4">
                    <div className="bg-white rounded-xl shadow-lg border border-gray-100 p-6 w-full max-w-md animate-in zoom-in-95 duration-150">
                        <h3 className="text-base font-semibold text-gray-700 mb-4 flex items-center gap-2">
                            <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="text-orange-500">
                                <path d="M11 4H4a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-7"></path>
                                <path d="M18.5 2.5a2.121 2.121 0 0 1 3 3L12 15l-4 1 1-4 9.5-9.5z"></path>
                            </svg>
                            Edit Peralatan
                        </h3>

                        {/* Error message */}
                        {editError && (
                            <div className="mb-4 p-3 bg-red-50 border border-red-100 rounded-lg text-red-600 text-sm">
                                {editError}
                            </div>
                        )}

                        {/* Form fields */}
                        <div className="space-y-4">
                            <div>
                                <label className="block text-xs text-gray-500 mb-1.5">Nama Peralatan</label>
                                <input
                                    type="text"
                                    value={editData.name}
                                    onChange={(e) => setEditData({ ...editData, name: e.target.value.toUpperCase() })}
                                    className="w-full px-3 py-2 bg-gray-50 border border-gray-200 rounded-lg text-sm focus:bg-white focus:border-orange-300 focus:outline-none focus:ring-2 focus:ring-orange-100 transition-all uppercase"
                                    placeholder="Contoh: PMS BUS A"
                                    disabled={isSaving}
                                />
                            </div>
                            <div>
                                <label className="block text-xs text-gray-500 mb-1.5">Bay</label>
                                <input
                                    type="text"
                                    value={editData.bay}
                                    onChange={(e) => setEditData({ ...editData, bay: e.target.value.toUpperCase() })}
                                    className="w-full px-3 py-2 bg-gray-50 border border-gray-200 rounded-lg text-sm focus:bg-white focus:border-orange-300 focus:outline-none focus:ring-2 focus:ring-orange-100 transition-all uppercase"
                                    placeholder="Contoh: BREBES 1"
                                    disabled={isSaving}
                                />
                            </div>
                        </div>

                        {/* Preview */}
                        <div className="mt-4 p-3 bg-orange-50/50 rounded-lg border border-orange-100/50">
                            <span className="text-xs text-gray-500">Hasil: </span>
                            <span className="text-sm font-medium text-gray-700">
                                {editData.name.trim() && editData.bay.trim()
                                    ? `${editData.name.trim().toUpperCase()} ${editData.bay.trim().toUpperCase()}`
                                    : '...'}
                            </span>
                        </div>

                        {/* Actions */}
                        <div className="flex justify-end gap-3 mt-6">
                            <button
                                onClick={cancelEdit}
                                disabled={isSaving}
                                className="px-4 py-2 text-sm font-medium text-gray-600 bg-gray-100 hover:bg-gray-200 rounded-lg transition-colors disabled:opacity-50"
                            >
                                Batal
                            </button>
                            <button
                                onClick={handleSaveEdit}
                                disabled={isSaving}
                                className="px-4 py-2 text-sm font-medium text-white bg-orange-500 hover:bg-orange-600 rounded-lg transition-colors shadow-sm disabled:opacity-50 flex items-center gap-2"
                            >
                                {isSaving ? (
                                    <>
                                        <svg className="animate-spin h-4 w-4" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
                                            <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
                                            <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
                                        </svg>
                                        Menyimpan...
                                    </>
                                ) : (
                                    'Simpan'
                                )}
                            </button>
                        </div>
                    </div>
                </div>
            )}
        </>
    );
}
