// Interface definition
export interface RiwayatManuver {
    id: string;
    judul_manuver: string;
    tanggal: string;
    gardu_induk: string;
    pengawas_pekerjaan: string;
    pengawas_k3: string;
    pengawas_manuver: string;
    pelaksana_manuver: string;
    dispatcher: string;
    created_at: string;
}

export const DUMMY_RIWAYAT_DATA: RiwayatManuver[] = [
    { id: 'dummy-1', judul_manuver: 'Pemeliharaan Rutin PMT 20kV Bay Feeder 1', tanggal: '2026-01-15', gardu_induk: 'GI Tanjung Priok', pengawas_pekerjaan: 'Ir. Budi Santoso', pengawas_k3: 'Ahmad Rizki', pengawas_manuver: 'Hendra Wijaya', pelaksana_manuver: 'Team A', dispatcher: 'Joni Dispatcher', created_at: '2026-01-15T08:00:00Z' },
    { id: 'dummy-2', judul_manuver: 'Instalasi CT Baru - Bay Incoming 150kV #1 @ GI Cilegon (Project 2026-Q1-001)', tanggal: '2026-01-12', gardu_induk: 'GI Cilegon', pengawas_pekerjaan: 'Drs. Sutrisno', pengawas_k3: 'Rahmat Hidayat', pengawas_manuver: 'Agus Setiawan', pelaksana_manuver: 'Team B', dispatcher: 'Siti Control', created_at: '2026-01-12T14:30:00Z' },
    { id: 'dummy-3', judul_manuver: 'Isolasi Fault', tanggal: '2025-12-28', gardu_induk: 'GI Bekasi', pengawas_pekerjaan: 'Bambang P', pengawas_k3: 'Yudi', pengawas_manuver: 'Roni', pelaksana_manuver: 'Team C', dispatcher: 'Andi', created_at: '2025-12-28T03:15:00Z' },
    { id: 'dummy-4', judul_manuver: 'Manuver Switching PMS & PMT untuk Pekerjaan Hot Line Washing - Isolator 150kV Bay Trafo #2 (Include Pre-Test & Function Test Equipment)', tanggal: '2025-12-20', gardu_induk: 'GI Gandul', pengawas_pekerjaan: 'Ir. Widodo MT.', pengawas_k3: 'Dedi Supervisor K3', pengawas_manuver: 'Eko Prasetyo ST.', pelaksana_manuver: 'Team Operasi A', dispatcher: 'Maya Control Center', created_at: '2025-12-20T10:00:00Z' },
    { id: 'dummy-5', judul_manuver: 'Energize Bay Baru 🔌⚡', tanggal: '2025-11-30', gardu_induk: 'GI Durian', pengawas_pekerjaan: 'Pak Haji', pengawas_k3: 'Safety Man', pengawas_manuver: 'Operator 1', pelaksana_manuver: 'Team X', dispatcher: 'Dispatcher X', created_at: '2025-11-30T07:00:00Z' },
    { id: 'dummy-6', judul_manuver: 'Test PMT Bay 20kV #1', tanggal: '2025-11-15', gardu_induk: 'GI Serpong', pengawas_pekerjaan: 'Teguh', pengawas_k3: 'Firman', pengawas_manuver: 'Doni', pelaksana_manuver: 'Team D', dispatcher: 'Control', created_at: '2025-11-15T09:30:00Z' },
    { id: 'dummy-7', judul_manuver: 'De-Energize & Re-Energize Trafo Daya 60MVA [URGENT!!!] - Bay TU3 untuk Pemeriksaan Oil Level & Cooling System (Termasuk Isolasi Busbar & Testing Relay Protection)', tanggal: '2025-10-25', gardu_induk: 'GI Cibinong', pengawas_pekerjaan: 'Ir. Suparman PhD.', pengawas_k3: 'H. Ahmad K3 Inspector', pengawas_manuver: 'Bapak Hendra Koordinator', pelaksana_manuver: 'Maintenance Team Alpha', dispatcher: 'Ibu Sari @ Control Room', created_at: '2025-10-25T13:45:00Z' },
    { id: 'dummy-8', judul_manuver: 'Commissioning Bay PLTS 5MW', tanggal: '2025-10-10', gardu_induk: 'GI Cikupa', pengawas_pekerjaan: 'Farhan', pengawas_k3: 'Indra', pengawas_manuver: 'Joko', pelaksana_manuver: 'Team E', dispatcher: 'Lisa', created_at: '2025-10-10T11:00:00Z' },
    { id: 'dummy-9', judul_manuver: 'Switching PMS Bus Coupler (Bay BC#2) | Bypass Relay 87B', tanggal: '2025-09-18', gardu_induk: 'GI Karawang', pengawas_pekerjaan: 'Slamet Riyadi', pengawas_k3: 'Nanang K3', pengawas_manuver: 'Udin', pelaksana_manuver: 'Team F', dispatcher: 'Rizal Dispatcher', created_at: '2025-09-18T08:15:00Z' },
    { id: 'dummy-10', judul_manuver: 'Pemadaman Total GI untuk Annual Maintenance 2025', tanggal: '2025-08-30', gardu_induk: 'GI Pluit', pengawas_pekerjaan: 'Direktur Operasi', pengawas_k3: 'Manager K3', pengawas_manuver: 'Kepala Shift', pelaksana_manuver: 'All Teams', dispatcher: 'Chief Dispatcher', created_at: '2025-08-30T00:00:00Z' },
    { id: 'dummy-11', judul_manuver: 'Manuver PMS Incoming 150kV #1 & #2', tanggal: '2025-07-22', gardu_induk: 'GI Ancol', pengawas_pekerjaan: 'Wawan', pengawas_k3: 'Yanto', pengawas_manuver: 'Zaenal', pelaksana_manuver: 'Team G', dispatcher: 'Nina', created_at: '2025-07-22T14:00:00Z' },
    { id: 'dummy-12', judul_manuver: 'Replace Fuse 20kV Bay F-07', tanggal: '2025-06-15', gardu_induk: 'GI Cikarang', pengawas_pekerjaan: 'Andi', pengawas_k3: 'Benny', pengawas_manuver: 'Cecep', pelaksana_manuver: 'Team H', dispatcher: 'Dewi', created_at: '2025-06-15T10:30:00Z' },
    { id: 'dummy-13', judul_manuver: '⚠️ EMERGENCY MANUVER - Isolasi Bay Fault Feeder #5 & Restore via Bay BC (Manual/Local Operation Due to SCADA Failure) - Ref: WO-2025-05-001-EMERGENCY', tanggal: '2025-05-20', gardu_induk: 'GI Depok', pengawas_pekerjaan: 'Emergency Team Lead', pengawas_k3: 'Safety Officer On-Duty', pengawas_manuver: 'Senior Operator Night Shift', pelaksana_manuver: 'Quick Response Team', dispatcher: 'Emergency Dispatcher 24/7', created_at: '2025-05-20T02:30:00Z' },
    { id: 'dummy-14', judul_manuver: 'Loop Out/In Feeder 20kV', tanggal: '2025-04-18', gardu_induk: 'GI Tangerang', pengawas_pekerjaan: 'Fauzi', pengawas_k3: 'Gunawan', pengawas_manuver: 'Hadi', pelaksana_manuver: 'Team I', dispatcher: 'Eka', created_at: '2025-04-18T09:00:00Z' },
    { id: 'dummy-15', judul_manuver: 'Penambahan Bay 150kV Interconnection [PROJ-IC-2025-003] - Phase 1: Physical Installation, Phase 2: Testing & Commissioning - Total Duration: 3 Days', tanggal: '2025-03-25', gardu_induk: 'GI Bogor', pengawas_pekerjaan: 'Project Manager Agung', pengawas_k3: 'K3 Coordinator Tim', pengawas_manuver: 'Manuver Coordinator Yusuf', pelaksana_manuver: 'Contractor + Internal Team', dispatcher: 'Senior Dispatcher Panel', created_at: '2025-03-25T07:30:00Z' },
    { id: 'dummy-16', judul_manuver: 'Inspection LA Bay Trafo 1', tanggal: '2025-02-14', gardu_induk: 'GI Kelapa Gading', pengawas_pekerjaan: 'Ikhsan', pengawas_k3: 'Jajang', pengawas_manuver: 'Kamil', pelaksana_manuver: 'Team J', dispatcher: 'Faisal', created_at: '2025-02-14T08:45:00Z' },
    { id: 'dummy-17', judul_manuver: 'Manuver Transfer Beban dari Bay F-01 ke F-02 via Tie CB#3 | Testing Automatic Load Transfer Scheme (ALTS) - Rev.2.1', tanggal: '2025-01-30', gardu_induk: 'GI Cengkareng', pengawas_pekerjaan: 'Ir. Lukman Hakim MSc', pengawas_k3: 'Safety Inspector Certified', pengawas_manuver: 'Operator Senior License A', pelaksana_manuver: 'Operation & Protection Team', dispatcher: 'Main Control Dispatcher', created_at: '2025-01-30T13:15:00Z' },
    { id: 'dummy-18', judul_manuver: 'Cleaning Busbar 20kV (Section A,B,C)', tanggal: '2024-12-20', gardu_induk: 'GI Pancoran', pengawas_pekerjaan: 'Lukman', pengawas_k3: 'Mukti', pengawas_manuver: 'Nanda', pelaksana_manuver: 'Team K', dispatcher: 'Gita', created_at: '2024-12-20T07:00:00Z' },
    { id: 'dummy-19', judul_manuver: 'Manuver PMS untuk Pekerjaan Hot Stick Method', tanggal: '2024-11-15', gardu_induk: 'GI Senayan', pengawas_pekerjaan: 'Omar', pengawas_k3: 'Putra', pengawas_manuver: 'Qomar', pelaksana_manuver: 'Team L', dispatcher: 'Hani', created_at: '2024-11-15T09:45:00Z' },
    { id: 'dummy-20', judul_manuver: 'Replace Battery Bank 110V DC - Bay Control & Protection System (Include Charger Testing, Ground Fault Detection, & Load Test) [Maintenance Schedule: Q4-2024]', tanggal: '2024-10-28', gardu_induk: 'GI Kramat Jati', pengawas_pekerjaan: 'Ir. Bambang Electrical Engineer', pengawas_k3: 'H. Rahmat K3 Certified Professional', pengawas_manuver: 'Koordinator Shift Mas Agung', pelaksana_manuver: 'Battery Specialist + Electrical Team', dispatcher: 'Dispatch Center - Night Shift', created_at: '2024-10-28T20:00:00Z' },
    { id: 'dummy-21', judul_manuver: 'Grounding Test Post Installation', tanggal: '2024-09-10', gardu_induk: 'GI Rawamangun', pengawas_pekerjaan: 'Reza', pengawas_k3: 'Satria', pengawas_manuver: 'Tono', pelaksana_manuver: 'Team M', dispatcher: 'Indah', created_at: '2024-09-10T08:00:00Z' },
    { id: 'dummy-22', judul_manuver: 'Commissioning Relay SEL-421 Bay Line 1, 2, & 3 + SCADA Integration Test', tanggal: '2024-08-22', gardu_induk: 'GI Menteng', pengawas_pekerjaan: 'Umar Faruq ST.', pengawas_k3: 'Vino Safety', pengawas_manuver: 'Wahyu Ops', pelaksana_manuver: 'Protection Team + IT', dispatcher: 'Control Jakarta Pusat', created_at: '2024-08-22T10:15:00Z' },
    { id: 'dummy-23', judul_manuver: 'Isolasi & Grounding Bay untuk Kalibrasi CT/PT Ratio Test (Include Megger Test, Tan Delta Test, & Polarity Check) - Equipment: Omicron CMC 356 + Doble M4000', tanggal: '2024-07-18', gardu_induk: 'GI Sudirman', pengawas_pekerjaan: 'Ir. Xavier Protection Specialist PhD.', pengawas_k3: 'Yusuf K3 Expert Certified International', pengawas_manuver: 'Bapak Zainudin Senior Operator 25 Years Experience', pelaksana_manuver: 'Testing & Commissioning Specialist Team International', dispatcher: 'Mrs. Sari Head of Control Room Operations', created_at: '2024-07-18T06:30:00Z' },
    { id: 'dummy-24', judul_manuver: 'Simulasi Black Start Procedure', tanggal: '2024-06-05', gardu_induk: 'GI Kebayoran', pengawas_pekerjaan: 'Yanto', pengawas_k3: 'Zaki', pengawas_manuver: 'Alif', pelaksana_manuver: 'Team N', dispatcher: 'Jasmine', created_at: '2024-06-05T05:00:00Z' },
    { id: 'dummy-25', judul_manuver: 'Testing & Acceptance New 150kV GIS Equipment', tanggal: '2024-05-15', gardu_induk: 'GI Kuningan', pengawas_pekerjaan: 'Bagus', pengawas_k3: 'Candra', pengawas_manuver: 'Dimas', pelaksana_manuver: 'Team O', dispatcher: 'Kartika', created_at: '2024-05-15T07:45:00Z' },
];
